// <auto-generated />
namespace Project_FTF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedapplicationDbContexttoLFContexteverywhere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedapplicationDbContexttoLFContexteverywhere));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051128195_Changed applicationDbContext to LFContext everywhere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
