// <auto-generated />
namespace Project_FTF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class additionstoseedmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additionstoseedmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201604141013432_additions to seed method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
